version: '3'

services:
  web:
    build: ./www
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html/
      - ./server-conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server-conf/apache2.conf:/etc/apache2/apache2.conf
      - ./server-conf/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: gofindme
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuserpassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data2:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"

