version: '3'
services:
  web:
    build: site
    ports :
     - "80:80"
    volumes:
     - ./www:/var/www/html/
     - ./public:/var/www/html/public
     - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
     - ./server/apache2.conf:/etc/apache2/apache2.conf
     - ./server/php.ini:/usr/local/etc/php/php.ini

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: gfmpwd
      POSTGRES_DB: gfm
      POSTGRES_USER: gofindme
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: cdanila@myges.fr
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_HOST: "postgres"
      PGADMIN_SERVER_PORT: 5432
      PGADMIN_SERVER_MAINTENANCE_DB: "gfm"
      PGADMIN_SERVER_USERNAME: "gofindme"
      PGADMIN_SERVER_PASSWORD: "gfmpwd"
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
