/categorie/add:
  controller: Categories
  action: newCategorie

/media/add:
  controller: Medias
  action: newMedia

/comments:
  controller: Comments
  action: comments

/post/add:
  controller: Posts
  action: newPost

/settings:
  controller: SiteSettings
  action: settings

/user:
  controller: User
  action: allUsers

/user/add-new-user:
  controller: User
  action: newUser

/user/edit-user:
  controller: User
  action: edit
