/:
  controller: Main
  action: home

/design-guide:
  controller: DesignGuide
  action: index

/categorie:
  controller: Categories
  action: allCategories

/categorie/add-new-categorie:
  controller: Categories
  action: newCategorie

/categorie/edit-categorie:
  controller: Categories
  action: editCategorie

/media:
  controller: Medias
  action: allMedias

/comments:
  controller: Comments
  action: allComments


/post:
  controller: Posts
  action: allPosts

/post/add-post:
  controller: Posts
  action: newPosts

/settings:
  controller: SiteSettings
  action: settings

/user:
  controller: User
  action: allUsers

/user/delete-user:
  controller: User
  action: delete

/user/add-new-user:
  controller: User
  action: newUser

/user/edit-user:
  controller: User
  action: edit

/register:
  controller: Security
  action: register

/login:
  controller: Security
  action: login

/login/logout:
  controller: Security
  action: logout

/login/recover-password:
  controller: Security
  action: forgetPassword

/login/get-code:
  controller: Security
  action: getCode

/login/init-password:
  controller: Security
  action: initPassword

/articles:
  controller: Articles
  action: allArticles

/articles/add-article:
  controller: Articles
  action: addArticles

/articles/edit-article:
  controller: Articles
  action: editArticles

