/:
  controller: Main
  action: home

/categorie:
  controller: Categories
  action: allCategories

/categorie/add-new-categorie:
  controller: Categories
  action: newCategorie

/categorie/edit-categorie:
  controller: Categories
  action: editCategorie

/media:
  controller: Medias
  action: allMedias

/comments:
  controller: Comments
  action: allComments

/posts:
  controller: Posts
  action: allPosts

/posts/post:
  controller: Posts
  action: post

/settings:
  controller: SiteSettings
  action: index

/user:
  controller: User
  action: allUsers

/user/delete-user:
  controller: User
  action: delete

/register:
  controller: Security
  action: register

/activate-account:
  controller: Security
  action: activateAccount

/user/edit-user:
  controller: User
  action: editUser

/login:
  controller: Security
  action: login

/login/logout:
  controller: Security
  action: logout

/recover-password:
  controller: Security
  action: requestResetPassword

/reset-password:
  controller: Security
  action: resetPassword

/articles:
  controller: Articles
  action: allArticles

/articles/add-article:
  controller: Articles
  action: addArticles

/articles/edit-article:
  controller: Articles
  action: editArticles

/blogs:
  controller: Blogs
  action: allBlogs

/blogs/add-blog:
  controller: Blogs
  action: addBlogs

/blogs/edit-blog:
  controller: Blogs
  action: editBlogs

/themes:
  controller: Themes
  action: allThemes

