/:
  controller: Main
  action: home

/categorie:
  controller: Categories
  action: allCategories

/categorie/add-new-categorie:
  controller: Categories
  action: newCategorie

/categorie/edit-categorie:
  controller: Categories
  action: editCategorie

/media:
  controller: Medias
  action: allMedias

/comments:
  controller: Comments
  action: comments


/post:
  controller: Posts
  action: allPosts

/settings:
  controller: SiteSettings
  action: settings

/user:
  controller: User
  action: allUsers

/user/delete-user:
  controller: User
  action: delete

/user/add-new-user:
  controller: User
  action: newUser

/user/edit-user:
  controller: User
  action: edit