/bo/dashboard:
  controller: Main
  action: home

/bo/medias:
  controller: Medias
  action: allMedias
  security: true
  roles: [admin, editor]

/register:
  controller: Security
  action: register

/activate-account:
  controller: Security
  action: activateAccount

/login:
  controller: Security
  action: login

/login/logout:
  controller: Security
  action: logout

/bo/categorie:
  controller: Categories
  action: allCategories

/bo/categorie/add-new-categorie:
  controller: Categories
  action: newCategorie

/bo/categorie/edit-categorie:
  controller: Categories
  action: editCategorie

/bo/posts:
  controller: Posts
  action: allPosts

/bo/posts/post:
  controller: Posts
  action: post

/bo/settings:
  controller: SiteSetting
  action: index

/bo/user:
  controller: User
  action: allUsers

/bo/user/view-user:
  controller: User
  action: viewUser

/bo/user/edit-user:
  controller: User
  action: editUser

/bo/user/edit-password:
  controller: User
  action: editPassword

/recover-password:
  controller: Security
  action: requestResetPassword

/reset-password:
  controller: Security
  action: resetPassword

/bo/articles:
  controller: Articles
  action: allArticles

/bo/articles/add-article:
  controller: Articles
  action: addArticles

/bo/articles/edit-article:
  controller: Articles
  action: editArticles

/bo/blogs:
  controller: Blogs
  action: allBlogs

/bo/blogs/add-blog:
  controller: Blogs
  action: addBlogs

/bo/blogs/edit-blog:
  controller: Blogs
  action: editBlogs

/bo/themes:
  controller: Themes
  action: allThemes

